# Generated by Django 5.1.3 on 2024-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
