# Generated by Django 5.1.3 on 2024-12-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comments'),
        ),
    ]
