# Generated by Django 5.1.3 on 2024-12-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comments_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='super_parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='main.comments'),
        ),
    ]
