# Generated by Django 5.1.3 on 2024-12-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
    ]
