# Generated by Django 5.1.3 on 2024-12-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ratings_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set(),
        ),
    ]
