# Generated by Django 5.1.3 on 2024-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ratings_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
