# Generated by Django 5.1.4 on 2024-12-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_album_id_alter_artist_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.artist'),
        ),
    ]
