# Generated by Django 5.1.4 on 2024-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_album_id_alter_genre_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
