# Generated by Django 5.1.4 on 2024-12-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_album_release_date_alter_song_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
    ]
